### ISSUE TITLE
Bosch oven - Cannot read properties of undefined  (reading 'allowedvalues')

### ISSUE THREAD

**Issue by MaGeHome** [iobroker-community-adapters/ioBroker.homeconnect#118]
Bosch Backofen
enumber: HBG7741B1/D3

TypeError: Cannot read properties of undefined  (reading 'min')

Protokoll:
`<html><body>
2024-01-09 20:04:42.037  - info: host.RaspberryPi-Home "system.adapter.homeconnect.0" enabled
2024-01-09 20:04:42.104  - info: host.RaspberryPi-Home instance system.adapter.homeconnect.0 started with pid 1244207
2024-01-09 20:04:44.030  - info:  homeconnect.0 (1244207) Plugin sentry Sentry Plugin disabled for this  process because sending of statistic data is disabled for the system
2024-01-09 20:04:44.149  - info:  homeconnect.0 (1244207) starting. Version 1.3.0 in  /opt/iobroker/node_modules/iobroker.homeconnect, node: v18.19.0,  js-controller: 5.0.17
2024-01-09 20:04:44.793  - info: homeconnect.0 (1244207) Found 2 devices
2024-01-09 20:04:46.845  - info: homeconnect.0 (1244207) 383120532656003304-001/programs/active: There is no program active.
2024-01-09 20:04:46.848  - info: homeconnect.0 (1244207) 383120532656003304-001/programs/active/options: There is no program active.
2024-01-09 20:04:46.854  - info: homeconnect.0 (1244207) 383120532656003304-001/programs/selected: There is no program selected.
2024-01-09 20:04:46.857  - info: homeconnect.0 (1244207) 383120532656003304-001/programs/selected/options: There is no program selected.
2024-01-09 20:04:46.867  - info: homeconnect.0 (1244207) No array: active
2024-01-09 20:04:46.872  - info: homeconnect.0 (1244207) No array: selected
2024-01-09 20:04:46.989  - info: homeconnect.0 (1244207) 333100539451004339/programs/selected/options: There is no program selected.
2024-01-09 20:04:46.994  - info: homeconnect.0 (1244207) 333100539451004339/programs/active: There is no program active.
2024-01-09 20:04:46.999  - info: homeconnect.0 (1244207) 333100539451004339/programs/active/options: There is no program active.
2024-01-09 20:04:47.003  - info: homeconnect.0 (1244207) 333100539451004339/programs/selected: There is no program selected.
2024-01-09 20:04:47.013  - info: homeconnect.0 (1244207) No array: active
2024-01-09 20:04:47.014  - info: homeconnect.0 (1244207) No array: selected
2024-01-09 20:04:47.014  - info: homeconnect.0 (1244207) No available programs found for: 333100539451004339
**2024-01-09 20:04:47.441  - error: homeconnect.0 (1244207) TypeError: Cannot read properties of undefined (reading 'min')
2024-01-09 20:04:47.442  - error: homeconnect.0 (1244207) TypeError: Cannot read properties of undefined (reading 'min')
at Homeconnect.getAPIValues (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:502:36)
2024-01-09 20:04:47.443  - error: homeconnect.0 (1244207) /programs/available/Cooking.Oven.Program.HeatingMode.HotAir
2024-01-09 20:04:47.443  - error:  homeconnect.0 (1244207)  {"data":{"key":"Cooking.Oven.Program.HeatingMode.HotAir","name":"Heißluft","options":[{"name":"Temperatur","key":"Cooking.Oven.Option.SetpointTemperature","constraints":{"min":30,"liveupdate":true,"max":275,"stepsize":1,"default":180},"unit":"°C","type":"Double"},{"name":"Dauer   anpassen","key":"BSH.Common.Option.Duration","constraints":{"min":1,"max":86400,"default":1,"liveupdate":true},"unit":"seconds","type":"Int"},{"name":"Startzeit","key":"BSH.Common.Option.StartInRelative","constraints":{"min":0,"max":86340,"default":0,"liveupdate":true},"unit":"seconds","type":"Int"},{"key":"Cooking.Oven.Option.FastPreHeat","type":"Boolean","name":"Schnellaufheizen"}]}}
2024-01-09 20:04:47.948  - error: homeconnect.0 (1244207) TypeError: Cannot read properties of undefined (reading 'min')
2024-01-09 20:04:47.949  - error: homeconnect.0 (1244207) TypeError: Cannot read properties of undefined (reading 'min')
at Homeconnect.getAPIValues (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:502:36)
2024-01-09 20:04:47.950  - error: homeconnect.0 (1244207) /programs/available/Cooking.Oven.Program.HeatingMode.TopBottomHeating
2024-01-09 20:04:47.950  - error:  homeconnect.0 (1244207)  {"data":{"key":"Cooking.Oven.Program.HeatingMode.TopBottomHeating","name":"Ober-/Unterhitze","options":[{"name":"Temperatur","key":"Cooking.Oven.Option.SetpointTemperature","constraints":{"min":30,"liveupdate":true,"max":300,"stepsize":1,"default":180},"unit":"°C","type":"Double"},{"name":"Dauer   anpassen","key":"BSH.Common.Option.Duration","constraints":{"min":1,"max":86400,"default":1,"liveupdate":true},"unit":"seconds","type":"Int"},{"name":"Startzeit","key":"BSH.Common.Option.StartInRelative","constraints":{"min":0,"max":86340,"default":0,"liveupdate":true},"unit":"seconds","type":"Int"},{"key":"Cooking.Oven.Option.FastPreHeat","type":"Boolean","name":"Schnellaufheizen"}]}}**
2024-01-09 20:04:59.408  - info: host.RaspberryPi-Home "system.adapter.homeconnect.0" disabled
2024-01-09 20:04:59.409  - info: host.RaspberryPi-Home stopInstance system.adapter.homeconnect.0 (force=false, process=true)
2024-01-09 20:04:59.414  - info: host.RaspberryPi-Home stopInstance system.adapter.homeconnect.0 send kill signal
2024-01-09 20:04:59.414  - info: homeconnect.0 (1244207) Got terminate signal TERMINATE_YOURSELF
2024-01-09 20:04:59.421  - info: homeconnect.0 (1244207) terminating
2024-01-09 20:04:59.423  - info: homeconnect.0 (1244207) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-01-09 20:04:59.925  - info: homeconnect.0 (1244207) terminating
2024-01-09 20:04:59.977  - info: host.RaspberryPi-Home instance system.adapter.homeconnect.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
</body>
</html>`

**Comment by TA2k** [comment]
Bitte die GitHub version testen ob das noch auftritt

**Comment by MaGeHome** [comment]
Mit der GitHub version :-)
Version 1.3.0 (non-npm: iobroker-community-adapters/ioBroker.homeconnect) in /opt/iobroker/node_modules/iobroker.homeconnect, node: v18.19.0, js-controller: 5.0.17

TypeError: Cannot read properties of undefined (reading 'allowedvalues')

Protokoll:
`<html><body>
2024-01-09 21:04:25.770  - info:  homeconnect.0 (1248139) Plugin sentry Sentry Plugin disabled for this  process because sending of statistic data is disabled for the system
2024-01-09 21:04:25.881  - info:  homeconnect.0 (1248139) starting. Version 1.3.0 (non-npm:  iobroker-community-adapters/ioBroker.homeconnect) in  /opt/iobroker/node_modules/iobroker.homeconnect, node: v18.19.0,  js-controller: 5.0.17
2024-01-09 21:04:26.502  - info: homeconnect.0 (1248139) Found 2 devices
2024-01-09 21:04:29.214  - info: homeconnect.0 (1248139) 333100539451004339/programs/selected: There is no program selected.
2024-01-09 21:04:29.225  - info: homeconnect.0 (1248139) 333100539451004339/programs/active: There is no program active.
2024-01-09 21:04:29.231  - info: homeconnect.0 (1248139) 333100539451004339/programs/active/options: There is no program active.
2024-01-09 21:04:29.238  - info: homeconnect.0 (1248139) 333100539451004339/programs/selected/options: There is no program selected.
2024-01-09 21:04:29.242  - info: homeconnect.0 (1248139) No array: active
2024-01-09 21:04:29.243  - info: homeconnect.0 (1248139) No array: selected
2024-01-09 21:04:29.245  - info: homeconnect.0 (1248139) No available programs found for: 333100539451004339
2024-01-09 21:04:29.373  - info: homeconnect.0 (1248139) 383120532656003304-001/programs/active/options: There is no program active.
2024-01-09 21:04:29.378  - info: homeconnect.0 (1248139) 383120532656003304-001/programs/active: There is no program active.
2024-01-09 21:04:29.381  - info: homeconnect.0 (1248139) 383120532656003304-001/programs/selected/options: There is no program selected.
2024-01-09 21:04:29.410  - info: homeconnect.0 (1248139) 383120532656003304-001/programs/selected: There is no program selected.
2024-01-09 21:04:29.414  - info: homeconnect.0 (1248139) No array: active
2024-01-09 21:04:29.419  - info: homeconnect.0 (1248139) No array: selected
2024-01-09 21:04:30.142  - error: homeconnect.0 (1248139) TypeError: Cannot read properties of undefined (reading 'allowedvalues')
2024-01-09 21:04:30.143  - error: homeconnect.0 (1248139) TypeError: Cannot read properties of undefined (reading 'allowedvalues')
at Homeconnect.getAPIValues (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:509:36)
2024-01-09 21:04:30.144  - error: homeconnect.0 (1248139) /programs/available/Cooking.Oven.Program.HeatingMode.TopBottomHeating
2024-01-09 21:04:30.144  - error:  homeconnect.0 (1248139)  {"data":{"key":"Cooking.Oven.Program.HeatingMode.TopBottomHeating","name":"Ober-/Unterhitze","options":[{"name":"Temperatur","key":"Cooking.Oven.Option.SetpointTemperature","constraints":{"min":30,"liveupdate":true,"max":300,"stepsize":1,"default":180},"unit":"°C","type":"Double"},{"name":"Dauer   anpassen","key":"BSH.Common.Option.Duration","constraints":{"min":1,"max":86400,"default":1,"liveupdate":true},"unit":"seconds","type":"Int"},{"name":"Startzeit","key":"BSH.Common.Option.StartInRelative","constraints":{"min":0,"max":86340,"default":0,"liveupdate":true},"unit":"seconds","type":"Int"},{"key":"Cooking.Oven.Option.FastPreHeat","type":"Boolean","name":"Schnellaufheizen"}]}}
2024-01-09 21:04:30.309  - error: homeconnect.0 (1248139) TypeError: Cannot read properties of undefined (reading 'allowedvalues')
2024-01-09 21:04:30.310  - error: homeconnect.0 (1248139) TypeError: Cannot read properties of undefined (reading 'allowedvalues')
at Homeconnect.getAPIValues (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:509:36)
2024-01-09 21:04:30.310  - error: homeconnect.0 (1248139) /programs/available/Cooking.Oven.Program.HeatingMode.HotAir
2024-01-09 21:04:30.311  - error:  homeconnect.0 (1248139)  {"data":{"key":"Cooking.Oven.Program.HeatingMode.HotAir","name":"Heißluft","options":[{"name":"Temperatur","key":"Cooking.Oven.Option.SetpointTemperature","constraints":{"min":30,"liveupdate":true,"max":275,"stepsize":1,"default":180},"unit":"°C","type":"Double"},{"name":"Dauer   anpassen","key":"BSH.Common.Option.Duration","constraints":{"min":1,"max":86400,"default":1,"liveupdate":true},"unit":"seconds","type":"Int"},{"name":"Startzeit","key":"BSH.Common.Option.StartInRelative","constraints":{"min":0,"max":86340,"default":0,"liveupdate":true},"unit":"seconds","type":"Int"},{"key":"Cooking.Oven.Option.FastPreHeat","type":"Boolean","name":"Schnellaufheizen"}]}}
</body>
</html>`

**Comment by TA2k** [comment]
Bitte nochmal installieren und testen

**Comment by MaGeHome** [comment]
Habe den Adapter komplett entfernt und neu von Github installiert. Die Fehler werden weiterhin ausgegeben.

**Comment by TA2k** [comment]
kannst du nochmal ein log zeigen

**Comment by MaGeHome** [comment]
Das aktuelle log.

`<html><body>
2024-01-11 10:37:33.711  - info: host.RaspberryPi-Home "system.adapter.homeconnect.0" enabled
2024-01-11 10:37:33.793  - info: host.RaspberryPi-Home instance system.adapter.homeconnect.0 started with pid 9419
2024-01-11 10:37:35.634  - info:  homeconnect.0 (9419) Plugin sentry Sentry Plugin disabled for this  process because sending of statistic data is disabled for the system
2024-01-11 10:37:35.761  - info:  homeconnect.0 (9419) starting. Version 1.3.0 (non-npm:  iobroker-community-adapters/ioBroker.homeconnect) in  /opt/iobroker/node_modules/iobroker.homeconnect, node: v18.19.0,  js-controller: 5.0.17
2024-01-11 10:37:36.416  - info: homeconnect.0 (9419) Found 2 devices
2024-01-11 10:37:36.674  - info: homeconnect.0 (9419) 383120532656003304-001/programs/active: There is no program active.
2024-01-11 10:37:36.971  - info: homeconnect.0 (9419) 333100539451004339/programs/active: There is no program active.
2024-01-11 10:37:37.152  - info: homeconnect.0 (9419) 333100539451004339/programs/active/options: There is no program active.
2024-01-11 10:37:37.193  - info: homeconnect.0 (9419) No array: active
2024-01-11 10:37:37.198  - info: homeconnect.0 (9419) No array: selected
2024-01-11 10:37:37.287  - info: homeconnect.0 (9419) 333100539451004339/programs/selected/options: There is no program selected.
2024-01-11 10:37:37.292  - info: homeconnect.0 (9419) 333100539451004339/programs/selected: There is no program selected.
2024-01-11 10:37:37.531  - info: homeconnect.0 (9419) 383120532656003304-001/programs/selected: There is no program selected.
2024-01-11 10:37:37.729  - error: homeconnect.0 (9419) TypeError: Cannot read properties of undefined (reading 'default')
2024-01-11 10:37:37.730  - error: homeconnect.0 (9419) TypeError: Cannot read properties of undefined (reading 'default')
at Homeconnect.getAPIValues (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:532:36)
at runNextTicks (node:internal/process/task_queues:60:5)
at process.processImmediate (node:internal/timers:447:9)
2024-01-11 10:37:37.732  - error: homeconnect.0 (9419) /programs/available/Cooking.Oven.Program.HeatingMode.HotAir
2024-01-11 10:37:37.732  - error:  homeconnect.0 (9419)  {"data":{"key":"Cooking.Oven.Program.HeatingMode.HotAir","name":"Heißluft","options":[{"name":"Temperatur","key":"Cooking.Oven.Option.SetpointTemperature","constraints":{"min":30,"liveupdate":true,"max":275,"stepsize":1,"default":180},"unit":"°C","type":"Double"},{"name":"Dauer   anpassen","key":"BSH.Common.Option.Duration","constraints":{"min":1,"max":86400,"default":1,"liveupdate":true},"unit":"seconds","type":"Int"},{"name":"Startzeit","key":"BSH.Common.Option.StartInRelative","constraints":{"min":0,"max":86340,"default":0,"liveupdate":true},"unit":"seconds","type":"Int"},{"key":"Cooking.Oven.Option.FastPreHeat","type":"Boolean","name":"Schnellaufheizen"}]}}
2024-01-11 10:37:37.745  - info:  homeconnect.0 (9419)  333100539451004339/settings/BSH.Common.Setting.AlarmClock: The rate  limit "50 calls in 1 minute" was reached. Requests are blocked during  the remaining period of 1 seconds..
2024-01-11 10:37:37.752  - info:  homeconnect.0 (9419)  383120532656003304-001/programs/available/Cooking.Oven.Program.HeatingMode.HotAirGrilling:  The rate limit "50 calls in 1 minute" was reached. Requests are blocked  during the remaining period of 1 seconds..
2024-01-11 10:37:37.766  - info:  homeconnect.0 (9419)  333100539451004339/settings/BSH.Common.Setting.PowerState: The rate  limit "50 calls in 1 minute" was reached. Requests are blocked during  the remaining period of 1 seconds..
2024-01-11 10:37:37.811  - info:  homeconnect.0 (9419)  383120532656003304-001/programs/available/Cooking.Oven.Program.HeatingMode.TopBottomHeating:  The rate limit "50 calls in 1 minute" was reached. Requests are blocked  during the remaining period of 1 seconds..
2024-01-11 10:37:37.814  - info:  homeconnect.0 (9419) 383120532656003304-001/programs/selected/options:  The rate limit "50 calls in 1 minute" was reached. Requests are blocked  during the remaining period of 1 seconds..
2024-01-11 10:37:37.862  - info:  homeconnect.0 (9419) 333100539451004339/programs: The rate limit "50  calls in 1 minute" was reached. Requests are blocked during the  remaining period of 1 seconds..
2024-01-11 10:37:38.078  - info:  homeconnect.0 (9419) 383120532656003304-001/programs/active/options:  The rate limit "50 calls in 1 minute" was reached. Requests are blocked  during the remaining period of 1 seconds..
2024-01-11 10:37:38.091  - info:  homeconnect.0 (9419)  333100539451004339/settings/BSH.Common.Setting.TemperatureUnit: The rate  limit "50 calls in 1 minute" was reached. Requests are blocked during  the remaining period of 1 seconds..
2024-01-11 10:37:38.097  - info:  homeconnect.0 (9419)  383120532656003304-001/programs/available/Cooking.Oven.Program.HeatingMode.PreheatOvenware:  The rate limit "50 calls in 1 minute" was reached. Requests are blocked  during the remaining period of 1 seconds..
2024-01-11 10:37:38.117  - info:  homeconnect.0 (9419)  383120532656003304-001/settings/BSH.Common.Setting.AlarmClock: The rate  limit "50 calls in 1 minute" was reached. Requests are blocked during  the remaining period of 1 seconds..
2024-01-11 10:37:38.137  - info:  homeconnect.0 (9419)  383120532656003304-001/programs/available/Cooking.Oven.Program.HeatingMode.KeepWarm:  The rate limit "50 calls in 1 minute" was reached. Requests are blocked  during the remaining period of 1 seconds..
2024-01-11 10:37:38.377  - info:  homeconnect.0 (9419)  383120532656003304-001/programs/available/Cooking.Oven.Program.HeatingMode.PreHeating:  The rate limit "50 calls in 1 minute" was reached. Requests are blocked  during the remaining period of 1 seconds..
2024-01-11 10:37:38.463  - info:  homeconnect.0 (9419)  383120532656003304-001/settings/BSH.Common.Setting.PowerState: The rate  limit "50 calls in 1 minute" was reached. Requests are blocked during  the remaining period of 1 seconds..
2024-01-11 10:37:38.507  - info:  homeconnect.0 (9419)  383120532656003304-001/programs/available/Cooking.Oven.Program.HeatingMode.BottomHeating:  The rate limit "50 calls in 1 minute" was reached. Requests are blocked  during the remaining period of 1 seconds..
2024-01-11 10:37:38.584  - info:  homeconnect.0 (9419)  333100539451004339/settings/BSH.Common.Setting.ChildLock: The rate limit  "50 calls in 1 minute" was reached. Requests are blocked during the  remaining period of 0 seconds..
2024-01-11 10:37:38.684  - info:  homeconnect.0 (9419)  383120532656003304-001/programs/available/Cooking.Oven.Program.HeatingMode.TopBottomHeatingEco:  The rate limit "50 calls in 1 minute" was reached. Requests are blocked  during the remaining period of 0 seconds..
2024-01-11 10:37:50.269  - info: host.RaspberryPi-Home "system.adapter.homeconnect.0" disabled
2024-01-11 10:37:50.270  - info: host.RaspberryPi-Home stopInstance system.adapter.homeconnect.0 (force=false, process=true)
2024-01-11 10:37:50.274  - info: host.RaspberryPi-Home stopInstance system.adapter.homeconnect.0 send kill signal
2024-01-11 10:37:50.275  - info: homeconnect.0 (9419) Got terminate signal TERMINATE_YOURSELF
2024-01-11 10:37:50.280  - info: homeconnect.0 (9419) terminating
2024-01-11 10:37:50.282  - info: homeconnect.0 (9419) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-01-11 10:37:50.783  - info: homeconnect.0 (9419) terminating
2024-01-11 10:37:50.851  - info: host.RaspberryPi-Home instance system.adapter.homeconnect.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)

</body>
</html>`

**Comment by TA2k** [comment]
sollte jetzt auch weg sein

**Comment by MaGeHome** [comment]
Die Fehler sind nun nicht mehr vorhanden. Vielen lieben Dank.
